# Generated by Django 6.0.3 on 2026-05-05 14:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('focal_person', models.CharField(blank=True, max_length=120)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
                ('purok', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=220)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('manager', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('Assembly', 'Assembly'), ('Health', 'Health'), ('Livelihood', 'Livelihood'), ('Education', 'Education'), ('Youth', 'Youth'), ('Clean-up', 'Clean-up'), ('Relief', 'Relief'), ('Cultural', 'Cultural'), ('Security', 'Security'), ('Other', 'Other')], default='Assembly', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('organizer', models.CharField(default='Barangay San Isidro Council', max_length=140)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('target_audience', models.CharField(blank=True, max_length=180)),
                ('expected_attendees', models.PositiveIntegerField(default=0)),
                ('budget_ceiling', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Planning', 'Planning'), ('Scheduled', 'Scheduled'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Planning', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('risk_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='eventcore.department')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='eventcore.venue')),
            ],
            options={
                'ordering': ['start_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=140)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('funding_source', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Approved', 'Approved'), ('Released', 'Released'), ('Liquidated', 'Liquidated')], default='Planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='eventcore.event')),
            ],
            options={
                'ordering': ['event', 'item'],
            },
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('purok', models.CharField(blank=True, max_length=80)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(default='Participant', max_length=80)),
                ('status', models.CharField(choices=[('Invited', 'Invited'), ('Confirmed', 'Confirmed'), ('Attended', 'Attended'), ('Absent', 'Absent')], default='Invited', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='eventcore.event')),
            ],
            options={
                'ordering': ['event', 'role', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('Advisory', 'Advisory'), ('Event', 'Event'), ('Health', 'Health'), ('Emergency', 'Emergency'), ('Meeting', 'Meeting')], default='Event', max_length=20)),
                ('body', models.TextField()),
                ('published_on', models.DateField(default=django.utils.timezone.localdate)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='eventcore.event')),
            ],
            options={
                'ordering': ['-published_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=140)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('custodian', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('Needed', 'Needed'), ('Requested', 'Requested'), ('Reserved', 'Reserved'), ('Ready', 'Ready'), ('Returned', 'Returned')], default='Needed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='eventcore.event')),
            ],
            options={
                'ordering': ['event', 'item'],
            },
        ),
    ]
