# Generated by Django 6.0.3 on 2026-05-06 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcore', '0002_event_approval_notes_event_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_name', models.CharField(blank=True, max_length=160)),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=3)),
                ('comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='eventcore.event')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('purok', models.CharField(blank=True, max_length=80)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Confirmed', 'Confirmed'), ('Attended', 'Attended'), ('Absent', 'Absent')], default='Registered', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='eventcore.event')),
            ],
            options={
                'ordering': ['event', 'full_name'],
            },
        ),
    ]
