# Generated by Django 6.0.3 on 2026-05-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcore', '0003_feedback_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20),
        ),
    ]
