# Generated by Django 6.0.3 on 2026-05-12 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('Assembly', 'Assembly'), ('Health', 'Health'), ('Livelihood', 'Livelihood'), ('Youth', 'Youth'), ('Clean-up', 'Clean-up'), ('Relief', 'Relief'), ('Cultural', 'Cultural'), ('Other', 'Other')], default='Assembly', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(default='Barangay San Isidro', max_length=180)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('organizer', models.CharField(blank=True, max_length=160)),
                ('target_audience', models.CharField(blank=True, max_length=180)),
                ('expected_attendees', models.PositiveIntegerField(default=0)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Scheduled', 'Scheduled'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Planning', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_official', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_events', to='barangay.barangayofficial')),
            ],
            options={
                'ordering': ['start_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(default='Participant', max_length=80)),
                ('status', models.CharField(choices=[('Invited', 'Invited'), ('Confirmed', 'Confirmed'), ('Attended', 'Attended'), ('Absent', 'Absent')], default='Invited', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='barangay.event')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_attendances', to='barangay.resident')),
            ],
            options={
                'ordering': ['event', 'role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=140)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('assigned_to', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('Needed', 'Needed'), ('Requested', 'Requested'), ('Reserved', 'Reserved'), ('Ready', 'Ready'), ('Returned', 'Returned')], default='Needed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='barangay.event')),
            ],
            options={
                'ordering': ['event', 'item'],
            },
        ),
    ]
