# Generated by Django 6.0.3 on 2026-05-12 04:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0002_event_eventattendee_eventresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(max_length=160)),
                ('module', models.CharField(blank=True, max_length=80)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BarangayProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Barangay San Isidro', max_length=160)),
                ('city', models.CharField(default='Surigao City', max_length=120)),
                ('province', models.CharField(default='Surigao del Norte', max_length=120)),
                ('region', models.CharField(default='Caraga', max_length=120)),
                ('classification', models.CharField(default='Rural barangay', max_length=120)),
                ('psgc_code', models.CharField(blank=True, max_length=30)),
                ('correspondence_code', models.CharField(blank=True, max_length=30)),
                ('population_2020', models.PositiveIntegerField(default=629)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Barangay Profile',
                'verbose_name_plural': 'Barangay Profile',
            },
        ),
        migrations.CreateModel(
            name='ResidentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email'), ('Posted', 'Posted')], default='Posted', max_length=20)),
                ('audience', models.CharField(default='All residents', max_length=160)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Ready', 'Ready'), ('Sent', 'Sent')], default='Draft', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('certificate_type', models.CharField(choices=[('Barangay Clearance', 'Barangay Clearance'), ('Certificate of Indigency', 'Certificate of Indigency'), ('Certificate of Residency', 'Certificate of Residency'), ('Business Clearance', 'Business Clearance')], default='Barangay Clearance', max_length=40)),
                ('applicant_name', models.CharField(blank=True, max_length=160)),
                ('purpose', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Claimed', 'Claimed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('issued_on', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='barangay.resident')),
            ],
            options={
                'ordering': ['-issued_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160)),
                ('category', models.CharField(choices=[('Vaccination', 'Vaccination'), ('Medical Mission', 'Medical Mission'), ('Senior Citizen', 'Senior Citizen'), ('PWD', 'PWD'), ('Other', 'Other')], max_length=30)),
                ('record_date', models.DateField(default=django.utils.timezone.localdate)),
                ('details', models.TextField(blank=True)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_records', to='barangay.resident')),
            ],
            options={
                'ordering': ['-record_date', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('funding_source', models.CharField(blank=True, max_length=160)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Planning', max_length=20)),
                ('lead_official', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='barangay.barangayofficial')),
            ],
            options={
                'ordering': ['status', 'title'],
            },
        ),
    ]
